### PR TITLE
Remove immutable js

### PR DESCRIPTION
**Pull request by devvmh**
This is a draft PR that removes Immutable JS. 

Some context: when I first wrote this, I didn't fully understand how to best use ImmutableJS. Since then I've realized that it would be better to just remove it fully from this library, and perhaps to try to verify that I don't mutate anything statically or with tests.

That said, those tests don't exist yet, so this is a very invasive and potentially breaking change. I need to a) get a good testing env to work through the different uses of the lib and 
~~b) write unit tests for the reducers~~.

If anyone is reading this and wants to participate, please help me out by pulling the code for this branch onto your local machine and testing things out. A result of "still works!" would be great, and finding bugs would be even better. Of course, if you wrote me some unit tests, I'd love you forever.

Also if you use this lib and have code review comments feel free to drop them here :)

### CODE REVIEW

**Comment by devvmh** [comment]
This is ready to go.  I want to finish building a demo app that'll give me greater confidence during breaking changes like this. So it'll happen, but it may be a few more weeks or months until this is merged.

**Comment by dzwiedziu-nkg** [comment]
I no see benefits from using ImmutableJS in this case but I think using toJS in selectors provides unnecesairy CPU consumption. I suggest: return immutable object from selectors or remove ImmutableJS whole.

**Comment by devvmh** [comment]
Yes, agreed, the purpose of this PR is to remove ImmutableJS

**Comment by devvmh** [comment]
OK, this is rebased off the latest master, the unit tests pass, and I've done some cursory testing with a [demo app](github.com/devvmh/demo-redux-crud-store). I'm going to merge this to master. Anyone who is following this PR: please try out the code and get in touch to let me know how it goes.

**Pull request merged**
