### PR TITLE
Configurable cache period (fixes #56)

### LINKED ISSUE #56: Cache period should be configurable
Currently the 10 minute cache period is not configurable.

See https://github.com/devvmh/redux-crud-store/blob/master/src/reducers.js#L96, https://github.com/devvmh/redux-crud-store/blob/master/src/reducers.js#L175, https://github.com/devvmh/redux-crud-store/blob/master/src/sagas.js#L21, and
https://github.com/devvmh/redux-crud-store/blob/master/src/selectors.js#L38

Perhaps a quick fix (instead of allowing a tunable caching period) is to provide a flag for switching caching on/off.

### PR DESCRIPTION
**Pull request by devvmh**

### CODE REVIEW

**Comment by oertels** [comment]
Great and needed feature, is there a reason why it hasn't been merged yet?

**Comment by devvmh** [comment]
@schneck thanks for the ping! Could you try this on a local instance and give me any feedback? if it works for you, I'm happy to merge

I'm hesitant to merge too many features without someone actually using them in a real world case - I only have a demo app now since I've left the company I developed this at

**Comment by oertels** [comment]
Sure, I'm testing it locally now, but I'm not sure whether I'm doing it right:

`fetchRecord('user', id, '/accounts/users/1/', {}, { interval: 100000 }); // keep for 100 seconds`

Should invalidate this record every 100 seconds, right? This does not work, the garbage collector removes the key on first run. 
Setting the environment variable works fine, I set it to some seconds for testing: `REACT_APP_CACHE_PERIOD=6000`.

**Comment by oertels** [comment]
Okay,  I understand that only selectors are affected, so this should work, right?
`selectRecord('user', 1, state.models, {interval: 100000}); // keep for 100 seconds `
This does not work: the garbage collector removes the key on the first run.

**Comment by devvmh** [comment]
Unfortunately, this only works via env variables. I can't figure out a way to make the saga that dispatches actions, reducers, and selectors all use the same numbers other than via env vars.

Probably I should update the README explaining this haha

You said the env vars work for you right?

**Comment by devvmh** [comment]
Ooh, you're right, you should be able to override the selector behaviour, I see that comment now

**Comment by devvmh** [comment]
Maybe I should remove opts.interval from selectors...

**Comment by devvmh** [comment]
Yeah, interval is just to determine NEEDS_FETCH, which is just information that is passed to the component. It's theoretically unrelated to the cache period. So this is working as intended.

fairly ambiguous docs here: https://github.com/devvmh/redux-crud-store/blob/master/docs/API.md#selectaction-crudaction-crud-map-opts-object-selection

**Comment by devvmh** [comment]
@schneck I'm ready to merge this, but I'll wait for your signoff so I'm sure it's working for at least one user 😄

**Comment by oertels** [comment]
Ok I understand, so I can set the cache time in general, not for specific models. That's fine, just one thought about that: 
Maybe another PR could add the option to skip garbage collection completely (e.g. by setting the value the "0"?). In my case, I don't really need it, because the data redux-crud-store fetches stays there until I want to decide myself when to update.

Anyway, that might be a future option. This PR is working perfectly, I just tested again setting `REACT_APP_CACHE_PERIOD` and `REACT_APP_HALF_CACHE_PERIOD`. 

Thanks for your great work and this helpful lib!

**Pull request merged**
