### PR TITLE
Small word change in README

### PR DESCRIPTION
**Pull request by ryaninvents**
The way the README is worded implies that I have a choice of 1-4 of how I wish to integrate `redux-crud-store` into my application. This PR clarifies that these are not options but rather steps to be performed.

### CODE REVIEW

**Comment by devvmh** [comment]
I mean, technically I think my wording is more accurate (since you don't need to integrate in all four ways), but this is great, thank you!

Are you using redux-crud-store? Would you like to be a contributor to this repo?

Also, something I've been slowly considering is whether the README should reference `select`, which is a bit more complicated, or if it should prefer the simpler `selectCollection` and `selectRecord` functions. Do you have an opinion on this?

**Comment by ryaninvents** [comment]
Thanks for the feedback! I'm just starting to use this in my projects, so I may have more feedback over the coming weeks. I don't think it would yet be appropriate for me to be a "contributor", but I'll get up-to-speed as quickly as I can :)

Small note, would it be appropriate to add the README to the `"files"` entry in _package.json_? The current entry at npmjs.com does not have a README since the file is excluded.

**Comment by julienR2** [comment]
Hi ! From what I read here [https://docs.npmjs.com/files/package.json](https://docs.npmjs.com/files/package.json) the files entry is to list what to include in the project. However it is also specified that the README is always included anyway..
I don't know about good habits in terms of "files" entry, but I'm interested :)

**Comment by ryaninvents** [comment]
Oh good point... I ought to investigate further. I just noticed on npm that there's no README for this project, which may discourage folks from using it.

**Comment by julienR2** [comment]
Mm it seems there was actually an issue 1 month ago on the README detection at Npm https://github.com/npm/registry/issues/118.
Said to be resolved though.. We still have to investigate so..

**Comment by devvmh** [comment]
Yeah, the README should be included, that's worked fine. I'm not sure why it's not there right now. Maybe if I do another release it'll happen.

**Pull request merged**
