### PR TITLE
data envelope was being modified by a reducer. Fix and update tests

### LINKED ISSUE #64: TypeError: payload.forEach is not a function
I'm getting an error `TypeError: payload.forEach is not a function` parsing the response from a JSON API endpoint.

Specifically, [this response](https://gist.github.com/recurser/23fc68358024ff8bc84596a006821ad7) triggers the error. You can run [this gist](https://gist.github.com/recurser/6c0779420c004c659afb1d397abeb9c5) to see the error in action.

Removing the top-level `{"data": ...}` wrapping (ie. returning an array [like this](https://gist.github.com/recurser/3b9a6c97ba74349c92a9dd46aead3eff) instead of an object) works fine, but I don't have the option to change the data returned by the API endpoint unfortunately. [Here's a gist](https://gist.github.com/recurser/4b3aacf90e39fd29d26a5b9a0433148f) showing it working with the altered data structure.

As far as I can tell I'm complying with the `{ data: [ ... ] }` structure required by `redux-crud-store`. Any idea what I'm doing wrong here, or how I might be able get it working?

### PR DESCRIPTION
**Pull request by devvmh**
Also added deepFreeze(action) to reducer tests to avoid this error in future

Fixes #64

### CODE REVIEW

**Comment by devvmh** [comment]
@recurser @NullVoxPopuli can you try this branch and see if it fixes your issue?

I think you actually have to pull the code (on this branch), run `npm run build`, then change your demo app's package.json to

    "redux-crud-store": "/path/to/redux-crud-store"

e.g. mine looked like

    "redux-crud-store": "/Users/devin/git/redux-crud-store"

while testing. There is maybe another clever way to get npm to build the lib/ folder but I don't know it.

**Comment by recurser** [comment]
@devvmh I'll get onto testing this first thing in the morning - appreciate the quick turnaround here!

**Comment by recurser** [comment]
@devvmh I can confirm that this fixes the issue 👍

**Comment by devvmh** [comment]
OK, merging. I can publish any time but I'd like to merge #63 at the same time if possible.

**Pull request merged**
