### PR TITLE
fix #62 - bug preventing updates on records not already present

### LINKED ISSUE #62: Bug/expectation misalignment - Currently update requires record to be present locally.
image

Text from other issue: https://github.com/devvmh/redux-crud-store/issues/61#issuecomment-349383653

My code:
```js
  componentDidMount() {
    const { status, dispatch, location } = this.props;

    if (status.id === null) {
      const token = paramFromLocation(location, 'token');

      dispatch(invitationsAPI.update({id: token}));
    }
  }
```

where update is genericly defined as:
```js
    update: ({id, ...data}, params = {}) => updateRecord(
      model, id, `${path}/${id}`, data, params, {/* auth stuff */}
    ),
```

I'm just trying to do an 'accept invite' kind of workflow where the frontend is hit first so feedback can be presented to the user as fast as possible. (opposed to accepting the invite on the server (which would involve non-api server-routing as well)) :-)

### PR DESCRIPTION
**Pull request by devvmh**
@NullVoxPopuli, are you able to try this locally and see if it fixes your issue?

You should be able to enter this in package.json to make it work:

    "redux-crud-store": "devvmh/redux-crud-store#allow-update-on-non-present-record",

If it's not working try

    rm -rf node_modules/redux-crud-store
    npm install

### CODE REVIEW

**Comment by devvmh** [comment]
TODO add tests

**Comment by devvmh** [comment]
added tests. Tagging @NullVoxPopuli  as reviewer - I'd love to get this validated before merging and publishing as part of 5.4.1 along with #66

**Comment by NullVoxPopuli** [comment]
LGTM so far. will do a code test in a bit.

**Comment by devvmh** [comment]
@NullVoxPopuli ping

**Comment by NullVoxPopuli** [comment]
@devvmh haven't run in to any issues :+1:

**Pull request merged**
